version: 2.0

workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_SCHEME: "FakeWalletUSDT"
    scripts:
      - name: Проверка версии Xcode
        script: |
          xcodebuild -version
      - name: Создание exportOptions.plist
        script: |
          cat > $CM_BUILD_DIR/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>Apple Development</string>
              <key>provisioningProfiles</key>
              <dict>
                <key>FakeWalletUSDT</key>
                <string>YourProvisioningProfile</string>
              </dict>
            </dict>
          </plist>
          EOF
      - name: Проверка наличия exportOptions.plist
        script: |
          ls -la $CM_BUILD_DIR
      - name: Resolve dependencies
        script: |
          swift package resolve
      - name: Build project
        script: |
          xcodebuild -scheme $XCODE_SCHEME -sdk iphoneos -configuration Release -archivePath $CM_BUILD_DIR/FakeWalletUSDT.xcarchive archive -allowProvisioningUpdates
      - name: Проверка наличия архива
        script: |
          ls -la $CM_BUILD_DIR/FakeWalletUSDT.xcarchive
      - name: Create IPA
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/FakeWalletUSDT.xcarchive -exportPath $CM_BUILD_DIR/output -exportOptionsPlist $CM_BUILD_DIR/exportOptions.plist -allowProvisioningUpdates
      - name: Проверка наличия IPA
        script: |
          ls -la $CM_BUILD_DIR/output
    artifacts:
      - $CM_BUILD_DIR/output/*.ipa
