workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "FakeWalletUSDT.xcworkspace"
        XCODE_SCHEME: "FakeWalletUSDT"
    scripts:
      - name: Install dependencies
        script: |
          pod install
      - name: Build project
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME 
clean build
    artifacts:
      - build/ios/ipa/*.ipa

