version: 2.0

workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_SCHEME: "FakeWalletUSDT"
    scripts:
      - name: Resolve dependencies
        script: |
          swift package resolve
      - name: Build project
        script: |
          swift build -c release
      - name: Create IPA
        script: |
          xcodebuild -archivePath $CM_BUILD_DIR/FakeWalletUSDT.xcarchive -scheme FakeWalletUSDT -sdk iphoneos -configuration release -destination 'generic/platform=iOS'
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/FakeWalletUSDT.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
