version: 2.0

workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_SCHEME: "FakeWalletUSDT"
    scripts:
      - name: Проверка версии Xcode
        script: |
          xcodebuild -version
      - name: Создание exportOptions.plist
        script: |
          cat > $CM_BUILD_DIR/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>Apple Development</string>
              <key>provisioningProfiles</key>
              <dict>
                <key>com.your.bundle.id</key>
                <string>Your_Provisioning_Profile_Name</string>
              </dict>
            </dict>
          </plist>
          EOF
      - name: Архива