version: 2.0

workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_SCHEME: "FakeWalletUSDT"
    scripts:
      - name: Проверка версии Xcode
        script: |
          xcodebuild -version
      - name: Создание exportOptions.plist
        script: |
          cat > $CM_BUILD_DIR/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>Apple Development</string>
            </dict>
          </plist>
          EOF
      - name: Архивация проекта
        script: |
          xcodebuild -scheme $XCODE_SCHEME -sdk iphoneos -configuration Release -archivePath $CM_BUILD_DIR/FakeWalletUSDT.xcarchive archive -allowProvisioningUpdates -destination "generic/platform=iOS"
      - name: Создание IPA
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/FakeWalletUSDT.xcarchive -exportOptionsPlist $CM_BUILD_DIR/exportOptions.plist -exportPath $CM_BUILD_DIR/build
    artifacts:
      - build/*.ipa
