version: 2.0

workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_SCHEME: "FakeWalletUSDT"
    scripts:
      - name: Resolve dependencies
        script: |
          swift package resolve
      - name: Build project
        script: |
          xcodebuild -scheme FakeWalletUSDT -sdk iphoneos -configuration release -destination 'generic/platform=iOS' -archivePath $CM_BUILD_DIR/FakeWalletUSDT.xcarchive archive
      - name: Create IPA
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/FakeWalletUSDT.xcarchive -exportPath $CM_BUILD_DIR/FakeWalletUSDT.ipa -exportOptionsPlist $CM_SOURCE_DIR/exportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/FakeWalletUSDT.ipa 

